#-*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

# MASTER
  config.vm.define "Master" do |master|
    master.vm.box = "ubuntu/trusty64"
    master.vm.hostname = "master"
    # NETWORK
    config.vm.network "public_network", auto_config: false
    config.vm.provision "shell",
    run: "always",
    inline: "ifconfig eth1 192.168.1.254 netmask 255.255.255.0 up"
    config.vm.network "public_network", auto_config: false
    config.vm.provision "shell",
    run: "always",
    inline: "ifconfig eth2 192.168.10.254 netmask 255.255.255.0 up"
    # SHARED FOLDER
    master.vm.synced_folder "../../jarbas", "/home/vagrant/jarbas/", create: true
    # master.vm.synced_folder "../../../log", "/home/vagrant/jarbas/log", create: true

    master.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.memory = 256
    end

    master.vm.provision "shell", inline: <<-SHELL

    echo "-------------------------------- SETTING UP MASTER --------------------------------"

    echo "Criando diretórios"
    sudo mkdir -p /home/vagrant/log/attacker/
    sudo mkdir -p /home/vagrant/log/client/
    sudo mkdir -p /home/vagrant/log/monitored/
    sudo mkdir -p /home/vagrant/log/attacked/
    sudo mkdir -p /home/vagrant/log/hypervisor/

    # for i in `seq 1 6`
    # do
    #   sudo mkdir -p /home/vagrant/logs/clientes/0$i/ping/
    #   sudo mkdir -p /home/vagrant/logs/clientes/0$i/siege/
    # done

    echo "Update and Build Essentials"
    sudo apt-get -y update > /dev/null
    sudo apt-get install -y build-essential > /dev/null
    sudo apt-get install -y git > /dev/null

    echo "J.A.R.B.A.S."
    sudo ln -s /home/vagrant/jarbas/bin/jarbas /usr/bin/jarbas
    sudo chmod +x /home/vagrant/jarbas/bin/jarbas
    sudo chmod +x /home/vagrant/jarbas/bin/functions.sh

    echo "Installing SSHPASS"
    sudo apt-get -y install sshpass > /dev/null
    sudo sed -i 's,PermitRootLogin without-password,PermitRootLogin yes,g' /etc/ssh/sshd_config
    sudo echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
    sudo service ssh restart
    sudo rm /home/vagrant/.ssh/known_hosts
    echo "Status SSHPASS:"
    sshpass -V

    echo "-------------------------------- MASTER IS READY --------------------------------"

    SHELL
  end

# CLIENT
  config.vm.define "Client" do |client|
    client.vm.box = "ubuntu/trusty64"
    client.vm.hostname = "client"
    #NETWORK
    config.vm.network "public_network", auto_config: false
    config.vm.provision "shell",
    run: "always",
    inline: "ifconfig eth1 192.168.1.1 netmask 255.255.255.0 up"
    config.vm.network "public_network", auto_config: false
    config.vm.provision "shell",
    run: "always",
    inline: "ifconfig eth2 192.168.10.1 netmask 255.255.255.0 up"
    # SHARED FOLDER
    client.vm.synced_folder "../../jarbas", "/home/vagrant/jarbas/", create: true

    client.vm.provider "virtualbox" do |vb|
      vb.name = "client"
      vb.memory = 256
    end

    client.vm.provision "shell", inline: <<-SHELL

    echo "-------------------------------- SETTING UP CLIENT --------------------------------"

    echo "Criando diretórios"
    sudo mkdir -p /home/vagrant/log/client

    echo "Update and Build Essentials"
    sudo apt-get -y update > /dev/null
    sudo apt-get install -y build-essential > /dev/null
    sudo apt-get install -y git > /dev/null

    echo "J.A.R.B.A.S."
    sudo ln -s /home/vagrant/jarbas/bin/jarbas /usr/bin/jarbas
    sudo chmod +x /home/vagrant/jarbas/bin/jarbas
    sudo chmod +x /home/vagrant/jarbas/bin/functions.sh

    echo "Installing SSHPASS"
    sudo apt-get -y install sshpass > /dev/null
    sudo sed -i 's,PermitRootLogin without-password,PermitRootLogin yes,g' /etc/ssh/sshd_config
    sudo echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
    sudo service ssh restart
    sudo rm /home/vagrant/.ssh/known_hosts
    echo "Status SSHPASS:"
    sshpass -V

    echo "Installing EthTool"
    sudo apt-get -y install ethtool > /dev/null
    echo "Status EthTool: "
    ethtool --version

    echo "Installing TCP Dump"
    sudo apt-get -y install tcpdump > /dev/null
    echo "Status TCPDump: "
    tcpdump --version

    echo "Installing Siege"
    sudo apt-get -y install siege > /dev/null
    echo "Status Siege: "
    siege --version

    echo "-------------------------------- CLIENT IS READY --------------------------------"

    SHELL
  end
# ATTACKER
  config.vm.define "Attacker" do |attacker|
    attacker.vm.box = "ubuntu/trusty64"
    attacker.vm.hostname = "attacker"
    # NETWORK
    config.vm.network "public_network", auto_config: false
    config.vm.provision "shell",
    run: "always",
    inline: "ifconfig eth1 192.168.0.7 netmask 255.255.255.0 up"
    config.vm.network "public_network", auto_config: false
    config.vm.provision "shell",
    run: "always",
    # SHARED FOLDER
    inline: "ifconfig eth2 192.168.10.7 netmask 255.255.255.0 up"
    attacker.vm.synced_folder "../../jarbas", "/home/vagrant/jarbas/", create: true

    attacker.vm.provider "virtualbox" do |vb|
      vb.name = "attacker"
      vb.memory = 256
    end

    attacker.vm.provision "shell", inline: <<-SHELL

    echo "-------------------------------- SETTING UP ATTACKER --------------------------------"

    echo "Criando diretórios"
    sudo mkdir -p /home/vagrant/log/attacker

    echo "Update and Build Essentials"
    sudo apt-get -y update > /dev/null
    sudo apt-get install -y build-essential > /dev/null
    sudo apt-get install -y git > /dev/null

    echo "J.A.R.B.A.S."
    sudo ln -s /home/vagrant/jarbas/bin/jarbas /usr/bin/jarbas
    sudo chmod +x /home/vagrant/jarbas/bin/jarbas
    sudo chmod +x /home/vagrant/jarbas/bin/functions.sh

    echo "Installing SSHPASS"
    sudo apt-get -y install sshpass > /dev/null
    sudo sed -i 's,PermitRootLogin without-password,PermitRootLogin yes,g' /etc/ssh/sshd_config
    sudo echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
    sudo service ssh restart
    sudo rm /home/vagrant/.ssh/known_hosts
    echo "Status SSHPASS:"
    sshpass -V

    echo "Installing EthTool"
    sudo apt-get -y install ethtool > /dev/null
    echo "Status EthTool: "
    ethtool --version

    echo "Installing T50"
    wget --quiet "http://downloads.sourceforge.net/project/t50/t50-5.6/t50-5.6.6.tar.gz"
    tar -xvzf t50-5.6.6.tar.gz > /dev/null
    cd t50-5.6.6
    sudo ./configure > /dev/null
    sudo make > /dev/null
    sudo make install > /dev/null
    echo "Status T50: "
    t50 --version

    echo "-------------------------------- ATTACKER IS READY --------------------------------"

    SHELL
  end
  #
  # config.vm.define "gpcnmonitorado" do |gpcnmonitorado|
  #   gpcnmonitorado.vm.box = "ubuntu/trusty64"
  #   gpcnmonitorado.vm.hostname = "gpcnmonitorado"
  #   #Adaptador em modo
  #   config.vm.network "public_network", auto_config: false
  #   config.vm.provision "shell",
  #   run: "always",
  #   inline: "ifconfig eth1 192.168.10.201 netmask 255.255.255.0 up"
  #   config.vm.network "public_network", auto_config: false
  #
  #   gpcnmonitorado.vm.synced_folder "./monitorado/", "/gpcn/monitorado/", create: true
  #
  #   gpcnmonitorado.vm.provider "virtualbox" do |vb|
  #     vb.name = "gpcnmonitorado"
  #     vb.memory = 256
  #   end
  #
  #   gpcnmonitorado.vm.provision "shell", inline: <<-SHELL
  #
  #   echo "-------------------------------- CONFIGURACAO DO MONITORADO --------------------------------"
  #
  #   echo "Criando diretórios"
  #   sudo mkdir -p /gpcn/monitorado/logs/collectl/
  #   sudo mkdir -p /gpcn/monitorado/logs/netstat/
  #   sudo mkdir -p /gpcn/monitorado/logs/sysbench/
  #   sudo mkdir -p /gpcn/monitorado/scripts/
  #
  #   echo "Instalando J.A.R.B.A.S"
  #   sudo apt-get install -y git > /dev/null
  #   git clone https://github.com/gpcnifpb/jarbas.git
  #   sudo chmod +x /home/vagrant/jarbas/bin/jarbas
  #   sudo chmod +x /home/vagrant/jarbas/bin/functions.sh
  #   sudo ln -s /home/vagrant/jarbas/bin/jarbas /usr/bin/jarbas
  #
  #   echo "Installing SSHPASS"
  #   sudo apt-get -y install sshpass > /dev/null
  #   sudo sed -i 's,PermitRootLogin without-password,PermitRootLogin yes,g' /etc/ssh/sshd_config
  #   sudo echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
  #   sudo service ssh restart
  #   sudo rm /home/vagrant/.ssh/known_hosts
  #   echo "Status SSHPASS:"
  #   sshpass -V
  #
  #   echo "Installing build essentials"
  #   sudo apt-get -y update > /dev/null
  #   sudo apt-get -y upgrade > /dev/null
  #   sudo apt-get install -y build-essential > /dev/null
  #
  #   echo "Installing Apache"
  #   sudo apt-get -y install apache2 > /dev/null
  #   echo "Status Apache:"
  #   apache2 -v
  #
  #   echo "Installing Collectl"
  #   sudo apt-get -y install collectl > /dev/null
  #   echo "Status Collectl:"
  #   collectl --version
  #
  #   echo "Installing Netstat"
  #   sudo apt-get -y install netstat-nat > /dev/null
  #   echo "Status Netstat:"
  #   netstat --version
  #
  #   echo "Installing Sysbench"
  #   sudo apt-get -y install sysbench > /dev/null
  #   echo "Status Sysbench:"
  #   sysbench --version
  #
  #   SHELL
  # end
  #
  # config.vm.define "gpcnatacado" do |gpcnatacado|
  #   gpcnatacado.vm.box = "ubuntu/trusty64"
  #   gpcnatacado.vm.hostname = "gpcnatacado"
  #   #Adaptador em modo
  #   config.vm.network "public_network", auto_config: false
  #   config.vm.provision "shell",
  #   run: "always",
  #   inline: "ifconfig eth1 192.168.0.200 netmask 255.255.255.0 up"
  #   config.vm.network "public_network", auto_config: false
  #   gpcnatacado.vm.synced_folder "./atacado/", "/gpcn/atacado/", create: true
  #
  #   gpcnatacado.vm.provider "virtualbox" do |vb|
  #     vb.name = "gpcnatacado"
  #     vb.memory = 256
  #   end
  #
  #   gpcnatacado.vm.provision "shell", inline: <<-SHELL
  #
  #   echo "-------------------------------- CONFIGURACAO DO ATACADO --------------------------------"
  #
  #   echo "Criando diretórios"
  #   sudo mkdir -p /gpcn/atacado/logs/collectl/
  #   sudo mkdir -p /gpcn/atacado/logs/netstat/
  #   sudo mkdir -p /gpcn/atacado/scripts/
  #
  #   echo "Installing SSHPASS"
  #   sudo apt-get -y install sshpass > /dev/null
  #   sudo sed -i 's,PermitRootLogin without-password,PermitRootLogin yes,g' /etc/ssh/sshd_config
  #   sudo echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
  #   sudo service ssh restart
  #   sudo rm /home/vagrant/.ssh/known_hosts
  #   echo "Status SSHPASS:"
  #   sshpass -V
  #
  #   echo "Instalando J.A.R.B.A.S"
  #   sudo apt-get install -y git > /dev/null
  #   git clone https://github.com/gpcnifpb/jarbas.git
  #   sudo chmod +x /home/vagrant/jarbas/bin/jarbas
  #   sudo chmod +x /home/vagrant/jarbas/bin/functions.sh
  #   sudo ln -s /home/vagrant/jarbas/bin/jarbas /usr/bin/jarbas
  #
  #   echo "Installing build essentials"
  #   sudo apt-get -y update > /dev/null
  #   sudo apt-get -y upgrade > /dev/null
  #   sudo apt-get install -y build-essential > /dev/null
  #
  #
  #   echo "Installing Apache"
  #   sudo apt-get -y install apache2 > /dev/null
  #   echo "Status Apache:"
  #   apache2 -v
  #
  #   echo "Installing Collectl"
  #   sudo apt-get -y install collectl > /dev/null
  #   echo "Status Collectl:"
  #   collectl --version
  #
  #   echo "Installing Netstat"
  #   sudo apt-get -y install netstat-nat > /dev/null
  #   echo "Status Netstat:"
  #   netstat --version
  #
  #   echo "Installing Stress-NG"
  #   sudo apt-get -y install stress-ng > /dev/null
  #   echo "Status Stress-ng:"
  #   stress-ng --version
  #
  #   SHELL
  # end
  #
end
