#!/bin/bash
. functions.sh
# Se DER ERRO USAR O dos2unix: dos2unix -k -o "nome do arquivo"

# Declaração de constantes
numRodadas="30"


if [ -z $1 ]
then
  echo "FAZER AQUI MENU DE ARGS"
  echo "Versão: 0.1"
  exit 1 ;
fi

while [[ $# > 0 ]]
do
  key="$1"

  case $key in
    --configure)
      machineType="$2"
      case $machineType  in
        atacado)
          echo "Atacado"
          break
          ;;
        monitorado)
          echo "Monitorado"
          break
          ;;
        atacante)
          echo "Atacante"
          break
          ;;
        cliente)
          echo "Cliente"
          break
          ;;
        figurantes)
          echo "Figurantes"
          break
          ;;
        hypervisor)
          echo "Hypervisor"
          break
          ;;
        *)
          echo "J.A.R.B.A.S LOG: Não digitou nenhum tipo da máquina." ; exit 1
      esac
      shift
      ;;

    run)
      if [ -z "$2" ]
      then
        echo "Executar o run com valores padrão."
        run $numRodadas
        exit 1;
      fi

      args="$2"
      case $args in
        -r| --rodadas)
          numRodadas="$3"

          if [ -z "$3" ]
          then
            echo "J.A.R.B.A.S LOG: Argumento Inválido depois de --rodadas (-r)" ; exit 1
          else
            echo "Rodadas: $numRodadas"
            run $numRodadas
          fi

          ;;

        *)
          echo "J.A.R.B.A.S LOG: Argumento Inválido depois do comando run" ; exit 1
      esac
      break
      ;;

    *)
    echo "J.A.R.B.A.S LOG: Argumento Inválido" ; exit 1
    ;;
  esac
  shift
done
