-*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

 config.vm.define "gpcnmaster" do |gpcnmaster|
   gpcnmaster.vm.box = "ubuntu/trusty64"
   gpcnmaster.vm.hostname = "gpcnmaster"
   #Adaptador em modo bridge
   config.vm.network "public_network", auto_config: false
   config.vm.provision "shell",
   run: "always",
   inline: "ifconfig eth1 192.168.0.254 netmask 255.255.255.0 up"
   config.vm.network "public_network", auto_config: false
   config.vm.provision "shell",
   run: "always",
   inline: "ifconfig eth2 192.168.10.254 netmask 255.255.255.0 up"

   gpcnmaster.vm.synced_folder "./master/", "/gpcn/master/", create: true

   gpcnmaster.vm.provider "virtualbox" do |vb|
     vb.name = "gpcnmaster"
     vb.memory = 256
   end

   gpcnmaster.vm.provision "shell", inline: <<-SHELL

     echo "-------------------------------- CONFIGURACAO DO MASTER --------------------------------"

     echo "Criando diretórios"
     sudo mkdir -p /gpcn/master/logs/monitorado/collectl/
     sudo mkdir -p /gpcn/master/logs/monitorado/netstat/
     sudo mkdir -p /gpcn/master/logs/monitorado/sysbench/
     sudo mkdir -p /gpcn/master/logs/atacado/collectl/
     sudo mkdir -p /gpcn/master/logs/atacado/netstat/
     sudo mkdir -p /gpcn/master/logs/clientes/
     sudo mkdir -p /gpcn/master/logs/hypervisor/
     sudo mkdir -p /gpcn/master/scripts/

     for i in `seq 1 6`
     do
     sudo mkdir -p /gpcn/master/logs/clientes/0$i/ping/
     sudo mkdir -p /gpcn/master/logs/clientes/0$i/siege/

     done
     echo "Instalando J.A.R.B.A.S"
     sudo apt-get install -y git > /dev/null
     git clone https://github.com/gpcnifpb/jarbas.git
     sudo chmod +x jarbas/project/jarbas
     sudo chmod +x jarbas/project/functions.sh
     sudo ln -s /home/vagrant/jarbas/Project/jarbas /usr/bin/jarbas

     echo "Installing build essentials"
     sudo apt-get -y update > /dev/null
     sudo apt-get -y upgrade > /dev/null
     sudo apt-get install -y build-essential > /dev/null

     echo "Installing SSHPASS"
     sudo apt-get -y install sshpass > /dev/null
     sudo sed -i 's,PermitRootLogin without-password,PermitRootLogin yes,g' /etc/ssh/sshd_config
     sudo echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
     sudo service ssh restart
     sudo rm /home/vagrant/.ssh/known_hosts
     echo "Status SSHPASS:"
     sshpass -V

   SHELL
 end

 config.vm.define "gpcnclient" do |gpcnclient|
   gpcnclient.vm.box = "ubuntu/trusty64"
   gpcnclient.vm.hostname = "gpcnclient"
   #Adaptador em modo
   config.vm.network "public_network", auto_config: false
   config.vm.provision "shell",
   run: "always",
   inline: "ifconfig eth1 192.168.0.1 netmask 255.255.255.0 up"
   config.vm.network "public_network", auto_config: false
   config.vm.provision "shell",
   run: "always",
   inline: "ifconfig eth2 192.168.10.1 netmask 255.255.255.0 up"
   gpcnclient.vm.synced_folder "./client/", "/gpcn/clientes/", create: true

   gpcnclient.vm.provider "virtualbox" do |vb|
     vb.name = "gpcnclient"
     vb.memory = 256
   end

   gpcnclient.vm.provision "shell", inline: <<-SHELL

     echo "-------------------------------- CONFIGURACAO DO CLIENT --------------------------------"

     echo "Criando diretórios"
     sudo mkdir -p /gpcn/clientes/logs/ping/
     sudo mkdir -p /gpcn/clientes/logs/siege/
     sudo mkdir -p /gpcn/clientes/scripts

     echo "Instalando J.A.R.B.A.S"
     sudo apt-get install -y git > /dev/null
     git clone https://github.com/gpcnifpb/jarbas.git
     sudo chmod +x jarbas/project/jarbas
     sudo chmod +x jarbas/project/functions.sh
     sudo ln -s /home/vagrant/jarbas/Project/jarbas /usr/bin/jarbas

     echo "Installing SSHPASS"
     sudo apt-get -y install sshpass > /dev/null
     sudo sed -i 's,PermitRootLogin without-password,PermitRootLogin yes,g' /etc/ssh/sshd_config
     sudo echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
     sudo service ssh restart
     sudo rm /home/vagrant/.ssh/known_hosts
     echo "Status SSHPASS:"
     sshpass -V

     echo "Installing build essentials"
     sudo apt-get -y update > /dev/null
     sudo apt-get -y upgrade > /dev/null
     sudo apt-get install -y build-essential > /dev/null

     echo "Installing EthTool"
     sudo apt-get -y install ethtool > /dev/null
     echo "Status EthTool: "
     ethtool --version

     echo "Installing TCP Dump"
     sudo apt-get -y install tcpdump > /dev/null
     echo "Status TCPDump: "
     tcpdump --version

     echo "Installing Siege"
     sudo apt-get -y install siege > /dev/null
     echo "Status Siege: "
     siege --version

   SHELL
 end

   config.vm.define "gpcnmonitorado" do |gpcnmonitorado|
   gpcnmonitorado.vm.box = "ubuntu/trusty64"
   gpcnmonitorado.vm.hostname = "gpcnmonitorado"
   #Adaptador em modo
   config.vm.network "public_network", auto_config: false
   config.vm.provision "shell",
   run: "always",
   inline: "ifconfig eth1 192.168.10.201 netmask 255.255.255.0 up"
   config.vm.network "public_network", auto_config: false

   gpcnmonitorado.vm.synced_folder "./monitorado/", "/gpcn/monitorado/", create: true

   gpcnmonitorado.vm.provider "virtualbox" do |vb|
     vb.name = "gpcnmonitorado"
     vb.memory = 256
   end

   gpcnmonitorado.vm.provision "shell", inline: <<-SHELL

     echo "-------------------------------- CONFIGURACAO DO MONITORADO --------------------------------"

     echo "Criando diretórios"
     sudo mkdir -p /gpcn/monitorado/logs/collectl/
     sudo mkdir -p /gpcn/monitorado/logs/netstat/
     sudo mkdir -p /gpcn/monitorado/logs/sysbench/
     sudo mkdir -p /gpcn/monitorado/scripts/

     echo "Instalando J.A.R.B.A.S"
     sudo apt-get install -y git > /dev/null
     git clone https://github.com/gpcnifpb/jarbas.git
     sudo chmod +x jarbas/project/jarbas
     sudo chmod +x jarbas/project/functions.sh
     sudo ln -s /home/vagrant/jarbas/Project/jarbas /usr/bin/jarbas

     echo "Installing SSHPASS"
     sudo apt-get -y install sshpass > /dev/null
     sudo sed -i 's,PermitRootLogin without-password,PermitRootLogin yes,g' /etc/ssh/sshd_config
     sudo echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
     sudo service ssh restart
     sudo rm /home/vagrant/.ssh/known_hosts
     echo "Status SSHPASS:"
     sshpass -V

     echo "Installing build essentials"
     sudo apt-get -y update > /dev/null
     sudo apt-get -y upgrade > /dev/null
     sudo apt-get install -y build-essential > /dev/null

     echo "Installing Apache"
     sudo apt-get -y install apache2 > /dev/null
     echo "Status Apache:"
     apache2 -v

     echo "Installing Collectl"
     sudo apt-get -y install collectl > /dev/null
     echo "Status Collectl:"
     collectl --version

     echo "Installing Netstat"
     sudo apt-get -y install netstat-nat > /dev/null
     echo "Status Netstat:"
     netstat --version

     echo "Installing Sysbench"
     sudo apt-get -y install sysbench > /dev/null
     echo "Status Sysbench:"
     sysbench --version

   SHELL
 end

   config.vm.define "gpcnatacado" do |gpcnatacado|
   gpcnatacado.vm.box = "ubuntu/trusty64"
   gpcnatacado.vm.hostname = "gpcnatacado"
   #Adaptador em modo
   config.vm.network "public_network", auto_config: false
   config.vm.provision "shell",
   run: "always",
   inline: "ifconfig eth1 192.168.0.200 netmask 255.255.255.0 up"
   config.vm.network "public_network", auto_config: false
   gpcnatacado.vm.synced_folder "./atacado/", "/gpcn/atacado/", create: true

   gpcnatacado.vm.provider "virtualbox" do |vb|
     vb.name = "gpcnatacado"
     vb.memory = 256
   end

   gpcnatacado.vm.provision "shell", inline: <<-SHELL

   echo "-------------------------------- CONFIGURACAO DO ATACADO --------------------------------"

     echo "Criando diretórios"
     sudo mkdir -p /gpcn/atacado/logs/collectl/
     sudo mkdir -p /gpcn/atacado/logs/netstat/
     sudo mkdir -p /gpcn/atacado/scripts/

     echo "Installing SSHPASS"
     sudo apt-get -y install sshpass > /dev/null
     sudo sed -i 's,PermitRootLogin without-password,PermitRootLogin yes,g' /etc/ssh/sshd_config
     sudo echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
     sudo service ssh restart
     sudo rm /home/vagrant/.ssh/known_hosts
     echo "Status SSHPASS:"
     sshpass -V

     echo "Instalando J.A.R.B.A.S"
     sudo apt-get install -y git > /dev/null
     git clone https://github.com/gpcnifpb/jarbas.git
     sudo chmod +x jarbas/project/jarbas
     sudo chmod +x jarbas/project/functions.sh
     sudo ln -s /home/vagrant/jarbas/Project/jarbas /usr/bin/jarbas

     echo "Installing build essentials"
     sudo apt-get -y update > /dev/null
     sudo apt-get -y upgrade > /dev/null
     sudo apt-get install -y build-essential > /dev/null


     echo "Installing Apache"
     sudo apt-get -y install apache2 > /dev/null
     echo "Status Apache:"
     apache2 -v

     echo "Installing Collectl"
     sudo apt-get -y install collectl > /dev/null
     echo "Status Collectl:"
     collectl --version

     echo "Installing Netstat"
     sudo apt-get -y install netstat-nat > /dev/null
     echo "Status Netstat:"
     netstat --version

     echo "Installing Stress-NG"
     sudo apt-get -y install stress-ng > /dev/null
     echo "Status Stress-ng:"
     stress-ng --version

   SHELL
 end

 config.vm.define "gpcnslave" do |gpcnslave|
   gpcnslave.vm.box = "ubuntu/trusty64"
   gpcnslave.vm.hostname = "gpcnslave"
   #Adaptador em modo
   config.vm.network "public_network", auto_config: false
   config.vm.provision "shell",
   run: "always",
   inline: "ifconfig eth1 192.168.0.7 netmask 255.255.255.0 up"
   config.vm.network "public_network", auto_config: false
   config.vm.provision "shell",
   run: "always",
   inline: "ifconfig eth2 192.168.10.7 netmask 255.255.255.0 up"
   gpcnslave.vm.synced_folder "./slave/", "/gpcn/atacante/", create: true

   gpcnslave.vm.provider "virtualbox" do |vb|
     vb.name = "gpcnslave"
     vb.memory = 256
   end

   gpcnslave.vm.provision "shell", inline: <<-SHELL

     echo "-------------------------------- CONFIGURACAO DO SLAVE --------------------------------"

     echo "Criando diretórios"
     sudo mkdir -p /gpcn/atacante/logs/
     sudo mkdir -p /gpcn/atacante/scripts/


     echo "Installing SSHPASS"
     sudo apt-get -y install sshpass > /dev/null
     sudo sed -i 's,PermitRootLogin without-password,PermitRootLogin yes,g' /etc/ssh/sshd_config
     sudo echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
     sudo service ssh restart
     sudo rm /home/vagrant/.ssh/known_hosts
     echo "Status SSHPASS:"
     sshpass -V

     echo "Instalando J.A.R.B.A.S"
     sudo apt-get install -y git > /dev/null
     git clone https://github.com/gpcnifpb/jarbas.git
     sudo chmod +x jarbas/project/jarbas
     sudo chmod +x jarbas/project/functions.sh
     sudo ln -s /home/vagrant/jarbas/Project/jarbas /usr/bin/jarbas

     echo "Installing build essentials"
     sudo apt-get -y update > /dev/null
     sudo apt-get -y upgrade > /dev/null
     sudo apt-get install -y build-essential > /dev/null

     echo "Installing EthTool"
     sudo apt-get -y install ethtool > /dev/null
     echo "Status EthTool: "
     ethtool --version

     echo "Installing T50"
     wget --quiet "http://downloads.sourceforge.net/project/t50/t50-5.6/t50-5.6.6.tar.gz"
     tar -xvzf t50-5.6.6.tar.gz > /dev/null
     cd t50-5.6.6
     sudo ./configure > /dev/null
     sudo make > /dev/null
     sudo make install > /dev/null
     echo "Status T50: "
     t50 --version

   SHELL
 end
end
